# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
  
  desc "Deploy a new version to firebase distribution"
  lane :firebaseDistribution do
    gradle(task: "assemble")
    firebase_app_distribution(
        app: "1:1023208811872:android:84d94bee0643fce0ed8205",
        service_credentials_file: "./androidfirstapp-5bc17-19a7f09523c0.json",
        groups: "test-fastlane",
        release_notes: "Lots of amazing new features to test out!"
      )
  end
end
